<?php

return [
    'array_syntax'                          => [
        'syntax' => 'short',
    ],
    'binary_operator_spaces'                => [
        'default'   => 'single_space',
        'operators' => [
            '=>' => 'align',
        ],
    ],
    'blank_line_after_namespace'            => true,
    'blank_line_after_opening_tag'          => true,
    'blank_line_before_statement'           => [
        'statements' => [
            'return',
        ],
    ],
    'braces'                                => [
        'allow_single_line_closure'                   => false,
        'position_after_control_structures'           => 'same',
        'position_after_functions_and_oop_constructs' => 'next',
    ],
    'cast_spaces'                           => [
        'space' => 'none',
    ],
    'class_attributes_separation'           => [
        'elements' => [
            'property',
            'method',
        ],
    ],
    'class_definition'                      => [
        'multiLineExtendsEachSingleLine' => false,
        'singleLine'                     => true,
    ],
    'combine_consecutive_unsets'            => true,
    'concat_space'                          => [
        'spacing' => 'one',
    ],
    'dir_constant'                          => true,
    'elseif'                                => true,
    'encoding'                              => true,
    'ereg_to_preg'                          => true,
    'explicit_indirect_variable'            => true,
    'full_opening_tag'                      => true,
    'function_typehint_space'               => true,
    'general_phpdoc_annotation_remove'      => [
        'annotations' => [
            'author',
            'access',
            'static',
        ],
    ],
    'header_comment'                        => false,
    'include'                               => true,
    'indentation_type'                      => true,
    'is_null'                               => true,
    'line_ending'                           => true,
    'lowercase_cast'                        => true,
    'lowercase_constants'                   => true,
    'lowercase_keywords'                    => true,
    'method_argument_space'                 => [
        'keep_multiple_spaces_after_comma' => false,
    ],
    'method_chaining_indentation'           => true,
    'native_function_casing'                => true,
    'new_with_braces'                       => true,
    'no_blank_lines_after_class_opening'    => true,
    'no_blank_lines_after_phpdoc'           => true,
    'no_closing_tag'                        => true,
    'no_empty_comment'                      => true,
    'no_empty_phpdoc'                       => true,
    'no_leading_import_slash'               => true,
    'no_leading_namespace_whitespace'       => true,
    'no_mixed_echo_print'                   => [
        'use' => 'echo',
    ],
    'no_short_bool_cast'                    => true,
    'no_short_echo_tag'                     => true,
    'no_trailing_comma_in_singleline_array' => true,
    'no_trailing_whitespace'                => true,
    'no_trailing_whitespace_in_comment'     => true,
    'no_unreachable_default_argument_value' => true,
    'no_unused_imports'                     => true,
    'no_whitespace_before_comma_in_array'   => true,
    'no_whitespace_in_blank_line'           => true,
    'object_operator_without_whitespace'    => true,
    'ordered_imports'                       => [
        'sortAlgorithm' => 'alpha',
    ],
    'phpdoc_indent'                         => true,
    'phpdoc_inline_tag'                     => true,
    'phpdoc_no_access'                      => true,
    'phpdoc_no_package'                     => true,
    'phpdoc_scalar'                         => true,
    'phpdoc_separation'                     => true,
    'phpdoc_single_line_var_spacing'        => true,
    'phpdoc_trim'                           => true,
    'phpdoc_types'                          => true,
    'psr4'                                  => true,
    'self_accessor'                         => true,
    'short_scalar_cast'                     => true,
    'single_blank_line_at_eof'              => true,
    'single_import_per_statement'           => true,
    'single_line_after_imports'             => true,
    'single_line_comment_style'             => [
        'comment_types' => [
            'hash',
        ],
    ],
    'single_quote'                          => true,
    'space_after_semicolon'                 => true,
    'standardize_not_equals'                => true,
    'switch_case_semicolon_to_colon'        => true,
    'switch_case_space'                     => true,
    'ternary_operator_spaces'               => true,
    'trailing_comma_in_multiline_array'     => true,
    'trim_array_spaces'                     => true,
    'visibility_required'                   => true,
];
